image: Visual Studio 2017 
branches: 
  only:
    - GuiForFtpClient
before_build:
  - nuget restore semester_3/GuiForFtpClient/GuiForFtpClient.sln
build:
  project: semester_3/GuiForFtpClient/GuiForFtpClient.sln
